/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DispatchesRouteImport } from './routes/dispatches'
import { Route as PioneersRouteImport } from './routes/pioneers'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesRoute = DispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => rootRouteImport,
} as any)
const PioneersRoute = PioneersRouteImport.update({
  id: '/pioneers',
  path: '/pioneers',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispatches': typeof DispatchesRoute
  '/pioneers': typeof PioneersRoute
  '/publications': typeof PublicationsRoute
  '/themes': typeof ThemesRoute
  '/news/$newsId': typeof NewsNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispatches': typeof DispatchesRoute
  '/pioneers': typeof PioneersRoute
  '/publications': typeof PublicationsRoute
  '/themes': typeof ThemesRoute
  '/news/$newsId': typeof NewsNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dispatches': typeof DispatchesRoute
  '/pioneers': typeof PioneersRoute
  '/publications': typeof PublicationsRoute
  '/themes': typeof ThemesRoute
  '/news/$newsId': typeof NewsNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dispatches'
    | '/pioneers'
    | '/publications'
    | '/themes'
    | '/news/$newsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dispatches'
    | '/pioneers'
    | '/publications'
    | '/themes'
    | '/news/$newsId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dispatches'
    | '/pioneers'
    | '/publications'
    | '/themes'
    | '/news/$newsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DispatchesRoute: typeof DispatchesRoute
  PioneersRoute: typeof PioneersRoute
  PublicationsRoute: typeof PublicationsRoute
  ThemesRoute: typeof ThemesRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches': {
      id: '/dispatches'
      path: '/dispatches'
      fullPath: '/dispatches'
      preLoaderRoute: typeof DispatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pioneers': {
      id: '/pioneers'
      path: '/pioneers'
      fullPath: '/pioneers'
      preLoaderRoute: typeof PioneersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DispatchesRoute: DispatchesRoute,
  PioneersRoute: PioneersRoute,
  PublicationsRoute: PublicationsRoute,
  ThemesRoute: ThemesRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
